# Generated by Django 5.2.5 on 2025-09-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(
                        help_text="Введите заголовок блоговой записи", max_length=100, verbose_name="Заголовок"
                    ),
                ),
                (
                    "content",
                    models.TextField(blank=True, help_text="Введите содержимое", null=True, verbose_name="Содержимое"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Добавьте изображение",
                        null=True,
                        upload_to="blogs/media",
                        verbose_name="Изображение",
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True, verbose_name="Дата создания")),
                (
                    "publication_sign",
                    models.BooleanField(help_text="Установите признак публикации", verbose_name="Признак публикации"),
                ),
                ("views_count", models.IntegerField(verbose_name="Количество просмотров")),
            ],
            options={
                "verbose_name": "Блоговая запись",
                "verbose_name_plural": "Блоговые записи",
            },
        ),
    ]
