# Generated by Django 5.2.5 on 2025-09-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="views_count",
            field=models.IntegerField(blank=True, null=True, verbose_name="Количество просмотров"),
        ),
    ]
