# Generated by Django 5.2.5 on 2025-09-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0002_alter_blog_views_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="views_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Укажите количество просмотров", verbose_name="Количество просмотров"
            ),
        ),
    ]
