# Generated by Django 5.2.5 on 2025-10-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_product_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="is_publish",
            field=models.BooleanField(default=False, verbose_name="Опубликовано"),
        ),
    ]
